name: Python package
on: [push]
#on:
 # release:
  #  types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
      #"3.7", "3.8", "3.9", "3.10",
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Python # Set Python version
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      # Install pip and pytest
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
    
      - name: Test with pytest
        run: |
          python3 -m coverage run -m pytest

      - name : Generate Coverage Report
        run: |
          python3 -m coverage report -m

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11' # the python version your want to build and upload your package with
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build package
      run: python -m build
    # - name: Publish new distributions to PyPI
    #   uses: pypa/gh-action-pypi-publish@release/v1
    #   with:
    #     password: ${{ secrets.PYPI_API_TOKEN }}
